### ISSUE TITLE
Multibyte Language Support

### ISSUE THREAD

**Issue by hangingman** [jhuapl-boss/heaviside#7]
Hello, 
I have tried to comment `.hsd` file in Japanese.
But, the compiler always translates our text into unicode hex characters.
I would like to output the text as is. How to do that ?

- helloworld.hsd
```
"""こんにちは AWS StepFunctions"""

version: "1.0"
timeout: 60

Pass()
    """Pass
    Comment"""
    data:
        {}
```

- helloworld.sfn
```
{
   "States": {
      "Pass": {
         "Type": "Pass",
         "Comment": "Comment",
         "Result": {},
         "End": true
      }
   },
   "StartAt": "Pass",
   "Comment": "\u7e3a\u8599\uff53\u7e3a\uff6b\u7e3a\uff61\u7e3a\uff6f AWS StepFunctions",
   "Version": "1.0",
   "TimeoutSeconds": 60
}
```

**Comment by movestill** [comment]
Hi, this should be addressed with the pull request listed above. Please give it a try and we'll merge it in if it works for you. I haven't verified that Unicode characters are valid in the SFN JSON, so we will wait on you before merging it in.

**Comment by Hiroyuki-Nagata** [comment]
@movestill Hi, thank you for your comments and pull request !
I tested `.hsd` file in Japanese. This time it looks working.

![image](https://user-images.githubusercontent.com/1238507/41584152-7f5c9cd4-73e1-11e8-98dd-db98b465266c.png)

**Comment by derek-pryor** [comment]
@hangingman I just merged the PR that @movestill started with updates that extends unicode support to not just comments but also task ARNs and Reference Paths. I will be releasing a new version of Heaviside (hopefully within the next couple of weeks) with several other improvements.

**Comment by derek-pryor** [comment]
@hangingman Heaviside 2.0 was just pushed to PyPi and contains this fix
